### ISSUE TITLE
voice activity ring not displaying correctly 

### ISSUE THREAD

**Issue by waterhulk09** [XYZenix/XYZenixThemes#169] opened 2024-11-04 04:10 UTC
![image](https://github.com/user-attachments/assets/65ba0dfc-8ff0-4b24-916a-13c8f61f6f04)
The ring is in an oval shape

**Comment by XYZenix** [comment] 2024-11-04 05:37
what theme and where is this

**Comment by waterhulk09** [comment] 2024-11-04 05:39
> what theme and where is this

it is at the bottom where your icon and name status is and the theme is dtm-16

**Comment by XYZenix** [comment] 2024-11-04 05:41
are you using any other themes/plugins? doesn't seem broken on my end

**Comment by waterhulk09** [comment] 2024-11-04 05:46
heres what im using but I dont think they affect anything as this issue did happen before when using this theme but after it was fixed
![image](https://github.com/user-attachments/assets/ae6bbd99-5f28-472b-9ef2-91aab96ff00a)
![Screenshot 2024-11-03 214321](https://github.com/user-attachments/assets/02762d4d-bd14-489b-be33-e18303fdbe62)
![image](https://github.com/user-attachments/assets/0d187f51-ad45-4d22-abac-5bf6d1c2e564)
![image](https://github.com/user-attachments/assets/dff076a4-2532-455b-8282-96d815212e90)
![image](https://github.com/user-attachments/assets/d5c94e70-c275-44b6-9d2a-97d256dde075)
![image](https://github.com/user-attachments/assets/0e607640-81be-421a-833a-9ac60b1b5756)
![image](https://github.com/user-attachments/assets/7b903610-5ad2-47ef-b0bb-02a55536b847)

**Comment by XYZenix** [comment] 2024-11-04 06:07
i tried checking with (nearly) all of those plugins and couldn't replicate this... i guess you could send a screenshot of the avatar element's html structure with all of its elements expanded while the speaking ring is visible? not sure how much that'll help

also unrelated but the 2015 user panel theme-addon is obsolete since it's just part of regular dtm-16 now

**Comment by waterhulk09** [comment] 2024-11-04 06:12
im sorry but how do I do that again I did it before but that was ages ago

**Comment by XYZenix** [comment] 2024-11-04 06:21
you open devtools with ctrl+shift+i then use this button in the top left corner of the devtools panel:
![image](https://github.com/user-attachments/assets/10a3fa9b-246a-4634-805d-35f6a41f8731)
to enable selecting an element by clicking it (it automatically disables itself once you select an element) and select the avatar, expand all of its inner elements in devtools, then trigger the speaking ring (fwiw i was using soundboard to do that)

i'm mostly working under the assumption some plugin is adding its own css that breaks the speaking ring though so this might not really help

**Comment by waterhulk09** [comment] 2024-11-05 00:53
![image](https://github.com/user-attachments/assets/3577213f-8752-4b39-9644-017f86d191e6)
ok here idk if this is the part you want but if not plz show me

**Comment by XYZenix** [comment] 2024-11-05 18:12
what about all the elements inside of that avatar element? i don't see anything different from that screenshot alone
just expand all of them and send a screenshot of that if possible

**Comment by waterhulk09** [comment] 2024-11-05 23:17
![Screenshot 2024-11-05 151023](https://github.com/user-attachments/assets/8f839c65-dc5d-4d37-8892-885ff77a332b)
![Screenshot 2024-11-05 151128](https://github.com/user-attachments/assets/247f2396-d960-4f54-9840-14bba0c70a1a)

**Comment by XYZenix** [comment] 2024-11-05 23:29
i still have no idea what's going on here... also, have you confirmed that this only happens with DTM-16 enabled?

**Comment by waterhulk09** [comment] 2024-11-05 23:54
yeah so found out it was a discord side issue or vencord or something as as you can see here 
![image](https://github.com/user-attachments/assets/727f4c42-e547-4f46-a06d-fb3d56d5d059)
this is me using the base theme

**Comment by XYZenix** [comment] 2024-11-06 00:00
sorry i can't help with that and since this isn't an issue with my themes i'll be closing this issue

**Closed by XYZenix** 2024-11-06 00:00 UTC

**Comment by waterhulk09** [comment] 2024-11-06 00:01
> sorry i can't help with that and since this isn't an issue with my themes i'll be closing this issue

yeah sorry so much about that no idea what it is then
