### ISSUE TITLE
[DTM-08] popout profiles are wiggly(sometimes)

### ISSUE THREAD

**Issue by TexNat** [XYZenix/XYZenixThemes#43] opened 2022-04-27 19:15 UTC
https://user-images.githubusercontent.com/64905176/165602230-76a60cf9-f7ae-40e5-9e9b-6591eaad3fc0.mp4

this doesn't always happen, but i can't seem to find any rhyme or reason as to why. it's consistent as long as you're clicking on the same user in the same server, so i imagine it has something to do with roles or nicknames

**Comment by TexNat** [comment] 2022-04-27 19:17
the extent of the wiggling also varies depending on the user

**Comment by XYZenix** [comment] 2022-07-12 04:08
i never got around to figuring out what caused this, and i have not been able to replicate it, does this still occur?

**Comment by aubymori** [comment] 2022-07-13 23:52
It seems to happen for popouts that are at the bottom of the screen.
So like the most recent user who posted in a channel.
![image](https://user-images.githubusercontent.com/44238627/178856082-8ea35764-780f-453b-b33e-35b67c9a7c8a.png)
(impossible to see but it IS shaking here)

**Comment by aubymori** [comment] 2022-07-13 23:52
oh also this is a dtm-16 issue as well

**Comment by TexNat** [comment] 2022-07-14 05:35
this does still happen yeah

**Comment by XYZenix** [comment] 2022-07-14 05:35
still can't reproduce and still can't figure out what causes it lol

**Comment by XYZenix** [comment] 2022-07-14 05:40
are you 1000% sure it's a bug with the theme and not some client mod or something because i am unable to get this to occur whatsoever

**Comment by aubymori** [comment] 2022-07-14 14:24
i am easily able to get it to occur with dtm-16 but with the default discord theme i cannot for the life of me get it to happen

**Comment by aubymori** [comment] 2022-07-14 14:26
again, when the popouts appear at the bottom of the screen, so try clicking the profile of the person who most recently messaged in that channel or on the bottom of the currently viewable part of the member list.

i actually do those things a lot and it gets REALLY annoying especially when im trying to click the profile of the person who most recently talked

**Comment by aubymori** [comment] 2022-07-14 14:28
https://user-images.githubusercontent.com/44238627/179006537-d3530073-b41e-417a-ad45-7cbf53e03c03.mp4

**Comment by XYZenix** [comment] 2022-07-14 19:04
this has been narrowed down to a bd plugin (BetterRoleColors), and idk if i can fix it so i'll leave this open for now

**Comment by XYZenix** [comment] 2023-01-28 09:24
due to the following factors:
- this is from april 2022, with no updates since july 2022
- discord's profile ui was reworked for the profile themes feature
- DTM-08 is being rewritten
i'm closing this issue

**Closed by XYZenix** 2023-01-28 09:24 UTC
Labels: bug, help needed, DTM-08
